# The URL the site will be built for
base_url = "https://lynndotpy.xyz/posts"
title = "lynndotpy.xyz"

# Sass compilation is required
compile_sass = true

# Optional: enable tags
taxonomies = [
    {name = "tags"},
]

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
# Put all your custom variables here
logo_text = "lynndotpy.xyz"
author = "Lynn Pepin"

# One of: blue, green, orange, pink, red, dark (background)
accent_color = "lynn-auto"
background_color = "auto" 
#logo_home_link = "/take/me/away!" # TODO

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    #{name = "blog", url = "$BASE_URL/posts"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "about", url = "$BASE_URL/about"},
    
    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/lynnpepin", newtab = true},
    {name = "gitlab", url = "https://gitlab.com/lynnpepin", newtab = true},
    {name = "mastodon", url = "https://mastodon.social/@lynndotpy", newtab = true},
]


# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = ""#"Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
favicon = "/favicon_package/favicon-32x32.png"
favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "main_only"

